### ISSUE TITLE
Broken in latest nightly

### ISSUE THREAD

**Issue by onur** [carllerche/h2#251]
Similar to https://github.com/hyperium/http/issues/192 h2 is also broken in latest nightly because of https://github.com/rust-lang/rust/pull/49305

<details>
<summary>Build log</summary>

```text
   Compiling h2 v0.1.3 (file:///tmp/h2)
error[E0034]: multiple applicable items in scope
  --> src/hpack/header.rs:66:33
   |
66 |                     let value = String::try_from(value)?;
   |                                 ^^^^^^^^^^^^^^^^ multiple `try_from` found
   |
   = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
   = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error[E0034]: multiple applicable items in scope
  --> src/hpack/header.rs:74:33
   |
74 |                     let value = String::try_from(value)?;
   |                                 ^^^^^^^^^^^^^^^^ multiple `try_from` found
   |
   = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
   = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error[E0034]: multiple applicable items in scope
  --> src/hpack/header.rs:78:33
   |
78 |                     let value = String::try_from(value)?;
   |                                 ^^^^^^^^^^^^^^^^ multiple `try_from` found
   |
   = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
   = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error[E0034]: multiple applicable items in scope
   --> src/hpack/header.rs:237:53
    |
237 |             Name::Authority => Ok(Header::Authority(String::try_from(value)?)),
    |                                                     ^^^^^^^^^^^^^^^^ multiple `try_from` found
    |
    = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
    = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error[E0034]: multiple applicable items in scope
   --> src/hpack/header.rs:239:47
    |
239 |             Name::Scheme => Ok(Header::Scheme(String::try_from(value)?)),
    |                                               ^^^^^^^^^^^^^^^^ multiple `try_from` found
    |
    = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
    = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error[E0034]: multiple applicable items in scope
   --> src/hpack/header.rs:240:43
    |
240 |             Name::Path => Ok(Header::Path(String::try_from(value)?)),
    |                                           ^^^^^^^^^^^^^^^^ multiple `try_from` found
    |
    = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
    = note: candidate #2 is defined in an impl of the trait `string::TryFrom` for the type `string::String<_>`

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0034`.
error: Could not compile `h2`.

To learn more, run the command again with --verbose.
```
</details>

**Comment by carllerche** [comment]
Yep, it will be broken until rustc fixes nightly. I wonder if we should pin the version of nightly like was done in [Tokio](https://github.com/tokio-rs/tokio/blob/master/.travis.yml#L23).

**Comment by tirkarthi** [comment]
This was reverted with https://github.com/rust-lang/rust/pull/49518

**Comment by carllerche** [comment]
Thanks for updating. I will close this now.
